### ISSUE TITLE
чеки

### ISSUE THREAD

**Issue by t3ran13** [golos-blockchain/golos#109]
1. Сделать возможность разбивать чек на несколько, например не более 10, или обналичивать на нескрлько акков, либо микс из акков и чеков. Т.е. не имея акка можно будет пользоваться переводом токенов чисто ключами, как в битке. Очень удобно.

2. Хранение чека жрет память ноды, хорошо бы чб сделать параметр с налогом за хранения чека, комсу отдавать делегатам

**Comment by ksantoprotein** [comment]
2. проще размер инвайта увеличить.

**Comment by t3ran13** [comment]
Пример:

В общем, у тебя паблик1 и приват 1, ты генеришь пары 2 и 3. К клайме юзаешь приватник 1 и указываешь сумму Х на паблик2 и сумму У на паблик 3. 

Вот чек и разбит на 2.
Жаль конечно что приватник1  палится, можно было бы переюзать

Обсуждение в телеге с пртмерами и обьяснениями https://t.me/golos_delegates/97422

**Comment by Lex-Ai** [comment]
https://github.com/golos-blockchain/golos/issues/111
