### ISSUE TITLE
transfer_invite

### ISSUE THREAD

**Issue by ksantoprotein** [golos-blockchain/golos#111]
сделать возможным переводить средства с одного инвайта на другой, при этом подписывать приватным ключом самого инвайта.

ops = []
op = {
	"from": invite_public_key,
	"to": receiver_invite_public_key,
	"amount": '10 GOLOS', 
	"memo": memo,
	"extensions": [],
	}
ops.append(['invite_transfer', op])

таким образом при передаче от одного инвайта к другому не раскрывается его приватный ключ как это сделано по наследству от VIZ в invite_claim.

если у инициатора на балансе остается 0 токенов, то этот инвайт удаляется из системы.
если receiver_invite_public_key нет, то создается инвайт новый (правда в поле создателя видимо помимо логина ввести публичный ключ инициатора)

но чтобы исключить спам сети путем передачи туда сюда (от одного инвайта другому и обратно) можно либо установить лимит на переводы. к примеру при генерации инвайта прописывать не только кто и когда его создал, но и последние действия с ним формата timestamp

"last_transfer": "2020-06-04T06:48:09",

и эта информация бы выдавалась при get_invite

и лимит сделать
а) параметром делегатов по образу как
 "invite_transfer_window": 3600,
 "invite_transfer_per_window": 2,
типа два перевода в час
б) сразу сделать константой. один перевод в 30 минут
с) высчитывать бендвиш как
"invite_market_bandwidth": "44568115103",
при этом в качестве аналога GolosPower (Сила голоса) использовать баланс инвайта, при этом при переносе токена вычитать бендвиш и передавать уже его в другой инвайт (иначе снова будет спам туда сюда)

это позволит юнитам использовать голос не создавая себе аккаунт на голосе (мертвый аккаунт). По сути пара приватный ключ + публичный ключ есть аналог криптокошелька, и предоставляя данные публичного ключа юнит сможет получать донаты/переводы непосредственно в свой кошель-инвайт не имея логина+пароля от аккаунта голоса. При этом всегда можно часть средств перевести на разовый инвайт, заклеймить его на биржи вывода или на иные цели.

если говорить про использование связки с донатами, то боты могут пойти по такому пути, получить в себя донат на типс, а потом часть своего ликвида использовать для генерации инвайта (забирая процент себе) и уже с инвайта делать перевод на публичный инвайт-кошелек юнита из внешнего мира. тогда в таком ключе пригодилась бы операция пополнения инвайта ликвидными токенами. что то вроде invite_donate
from: login
to: invite_public_key
balance: 10 GOLOS

**Comment by t3ran13** [comment]
Если не считать комсу, то у меня таже ишью создана. https://github.com/golos-blockchain/golos/issues/109
