### ISSUE TITLE
Система донатов как на Whaleshares

### ISSUE THREAD

**Issue by Lex-Ai** [golos-blockchain/golos#83]
Процент на вестинг поступает не в СГ/vesting_shares как сейчас, а на промежуточный баланс условно **accumulative_balance**

с этого спец. баланса, в течении срока цикла установленного делегатским параметром **claim_idleness_time** можно затребовать (**claim**) свою долю с вариантом вывода её на пополнение СГ/vesting_shares либо на **tip_balance** (баланс для донатинга за посты/комменты/любую иную активность к которой привяжут донаты разработчики-энтузиасты), 

если за установленный срок цикла **claim_idleness_time** операция **claim** не была выполнена аккаунтом, невостребованные токены переводятся в пул воркеров на развитие проекта. 

**tip_balance** можно пополнять ликвидными токенами с основного баланса, а забирать с **tip_balance** можно только в пополнение СГ.

Будут нужны
- делегатский параметр срока цикла **claim_idleness_time** в рамках которого пользователь должен затребовать свою долю (не менее 1 суток, по умолчанию 1 сутки)
- отдельный баланс **accumulative_balance** где токены идущие с эмиссии на вестинг будут ждать циклы сроком ожидания **claim_idleness_time** операции **claim** юзера, если её нет, отправка невостребованных токенов в пул воркерам
- операция **claim** постинг-ключом (получать с баланса **accumulative_balance** свою долю на вестинг, отправляя в пополнение СГ либо на **tip_balance** для донатинга) 
- операция **donate** постинг-ключом (вариант структуры операции в [комменте ниже](https://github.com/golos-blockchain/golos/issues/83#issuecomment-576524054))
для перевода токенов за посты/комменты/любую иную активность с tip_balance отправителя на tip_balance получателя (для циркуляции донатинга)
стоит взглянуть и на задачу/план реализации донатов на клиенте https://github.com/golos-blockchain/golos-ui/issues/20
- отдельный баланс **tip_balance** с которого операцией donate будет возможно отправлять вознаграждения за посты/комменты/любую иную активность

Нужно предусмотреть **макс. расширенное API** для получения списка донатов, чтобы позже была возможность реализовать рейтинг тех кто донатит, кто получает, за какие посты (выводить сумму донатов вместо той инфы что сейчас по апвоутам). В клиенте наверняка будет потребность вывода в профиле каждого юзера списка отправленных и полученных донатов, добавление ленты по типу "популярное" (с сортировкой по сумме донатов) и прочее...

**Comment by bitfag** [comment]
По операции donate следует заранее обсудить её структуру. Не стоит жёстко требовать наличия author, permlink для указания причины доната. Протокол надо сделать гибким, чтобы донат можно было сделать за что угодно. Думаю, нужны поля from, to, memo. Предполагается что memo должно быть в формате json, внутри которого будет инфа согласно некой спецификации которую мы придумаем, с версионированием API, напрмер морда может писать туда что-то типа:

```json
{"app": "golos-ui", "version": 1, "target": {"author": "lex", "permlink": "donations-is-cool"}, "comment": "Cool post"}
```
Т.е. обязательные поля только `app` и `version`, остальные поля могут меняться как угодно. На стороне ноды на этапе валидации я бы ввёл требование соблюдения формата данного протокола (memo в формате json, наличие обязательных полей). Требование указания app и API version обусловлено необходимостью всегда иметь возможность корректно спарсить данные.

При этом остаётся некоторая вероятность что приложение сменит API без поднятия версии (по глупости). Если есть возможность, можно запрограммировать ноду таким образом, чтобы она автоматически запоминала формат API для каждой версии, и не позволяла совершить транзакцию с изменённым форматом в рамках той же версии.
