### ISSUE TITLE
Возвращение user issued assets (UIA)

### ISSUE THREAD

**Issue by Lex-Ai** [golos-blockchain/golos#95]
Оценить, возможно ли это реанимировать? :)

В далёком 2017 на Голосе писали что готова поддержка UIA (user issued assets) https://golos.id/ru--golos/@golos/spisok-predpolagaemykh-izmenenii-predstoyashego-khf-v-odnom-poste-s-obnovlennoi-datoi-samogo-khf-na-10-iyulya-2017-12-00-gmt. 

С возможностью выпускать собственные токены и использовать их поверх блокчейна. 

Подробнее по правкам в код было тут https://github.com/GolosChain/golos/issues/115, видел и @gropox эксперементировал https://github.com/GolosChain/golos/issues/151, https://github.com/GolosChain/golos/issues/152, https://github.com/GolosChain/golos/issues/315

даже интерфейс был https://github.com/GolosChain/golos/issues/316

![](https://user-images.githubusercontent.com/26039472/33510096-5c4b757e-d708-11e7-84b3-3f29beeea5db.png)

что позволило бы торговать такими UIA на внутренней бирже Голоса, и отчасти привлечь желающих некой альтернативы битшарам, морды со шлюзом поверх Голос...

**Comment by t3ran13** [comment]
там еще были спорные вопросы на что завязывать ассеты на золотой или голос, мб дать выбирать?

И продажа коротких имен ассетов

**Comment by bitfag** [comment]
Не считаю что это хорошая идея, по сути предлагается втаскивать всю функциональность bitshares, это очень много логики без возможности оперативно её править.

**Comment by DimaBLCKCHND** [comment]
не обязательно перетаскивать весь функционал кмк, достаточно взять UIA и MPA , сам DEX у нас уже есть. Я думаю этого более чем достаточно для организации рынка к двум нативным активам. У нас уже есть декс из коробки, не развивать его, это упускать возможности

**Comment by bitfag** [comment]
Ну так это всё равно очень много логики, следовательно и потенциальных багов. Страшно представить какой там объём работы. Одна надежда на то, что в битшарах этот код более-менее причесали за годы. А ещё потом это всё в библиотеки и в ui надо будет запиливать. Не уверен, что в фондах хватит средств на оплату воркеров.
