### ISSUE TITLE
custom_json bandwidth isn't exposed in API

### ISSUE THREAD

**Issue by bitfag** [golos-blockchain/golos#96]
Expected to see custom_json bandwidth objects in `get_account` API call.

**Comment by Lex-Ai** [comment]
> Expected to see custom_json bandwidth objects in `get_account` API call.

Можешь уточнить, для чего это пригодится и в каком примерно виде ты ожидаешь ответ с API

**Comment by bitfag** [comment]
Для расчёта bandwidth. Ожидаю видеть аналогично другим типам bandwidth.
