### ISSUE TITLE
Портирование механики инвайтов/чеков по типу VIZ

### ISSUE THREAD

**Issue by Lex-Ai** [golos-blockchain/golos#98]
Инвайты может создать кто угодно, переведя в него токены. Их можно погасить или использовать в качестве инвайт-кода для упрощенной регистрации нового аккаунта. В первом случае токены поступают на счет аккаунта предъявителя, во втором случае токены конвертируются в Силу Голоса для нового аккаунта. Подробнее, описание тут - https://viz-doc.readthedocs.io/ru/latest/check.html

Реализация на VIZ

https://github.com/VIZ-Blockchain/viz-cpp-node/commit/1604894377b38ca24892cd3e0bcd1d8c49983adc, https://github.com/VIZ-Blockchain/viz-cpp-node/commit/b009b14f6c7365444d7d95453533708ad58a8edd, https://github.com/VIZ-Blockchain/viz-cpp-node/commit/0589792cdc2d259e42109a8573b4199410453314, https://github.com/VIZ-Blockchain/viz-cpp-node/commit/8930eb7e55f7474695302d05c9ace8ddc99c1307, https://github.com/VIZ-Blockchain/viz-cpp-node/commit/46c85c5881435f779f4c9726b39149ab64d77668

Описание invite_api
https://github.com/VIZ-Blockchain/viz-cookbook/wiki/Ru-Plugins-API#invite_api

Примеры использования JS-библиотеки для создания инвайта, регистрации через инвайт и погашения инвайта
https://github.com/VIZ-Blockchain/viz-cookbook/wiki/Ru-Code-examples#%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B0%D1%83%D1%87%D0%B5%D1%80%D0%B0-%D0%B8%D0%BD%D0%B2%D0%B0%D0%B9%D1%82-%D0%BA%D0%BE%D0%B4%D0%B0

<hr>

Также нужно добавление делегатского параметра минимальной суммы инвайта, по умолчанию 10 GOLOS (чтобы не абузили созданием инвайтов с "копейками").

**Comment by ksantoprotein** [comment]
еще одна ситуация с инвайтами - это время хранение использованных инвайтов. есть смысл установить делегатский параметр в неделю. ибо инвайт можно создать и тут же реализовать в себя тем самым провести некую спам атаку. при этом есть апи запрос который показывает инвайты списком и в том числе использованные и если в респонзе будут все все все использованные инвайты то это не есть гуд
